name: Caroline Bate Interiors
favicon: null
layout_spectrum: 0.50357
typography_spectrum: 0.69376
title: Caroline Bate Interiors
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a5a6a4'
    - '#e2e3e2'
    - '#efefef'
    - '#bcbdbb'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
