name: Caroline Bate Interiors
favicon: null
layout_spectrum: 0.5471132940147072
typography_spectrum: 0.40367607888765633
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.3434187101665884
  lightness: 0.8710028438363224
  saturation: 0.26409415481612086
  rhythmicContrast: 0.6716724326834083
purpose: []
