name: Caroline Bate Interiors
favicon: null
layout_spectrum: 0.50357
typography_spectrum: 0.69376
title: Caroline Bate Interiors
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a5a6a4'
    - '#e2e3e2'
    - '#efefef'
    - '#bcbdbb'
  brandStrength: 0.3434187101665884
  lightness: 0.8710028438363224
  saturation: 0.26409415481612086
  rhythmicContrast: 0.6716724326834083
purpose: []
